//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.42000 版自动生成。
// 
#pragma warning disable 1591

namespace H3.Wyeth.MainPush.com.h3yun.www {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BizObjectServiceSoap", Namespace="http://tempuri.org/")]
    public partial class BizObjectService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private Authentication authenticationValueField;
        
        private System.Threading.SendOrPostCallback CreateBizObjectsOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateBizObjectOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateBizObjectOperationCompleted;
        
        private System.Threading.SendOrPostCallback LoadBizObjectOperationCompleted;
        
        private System.Threading.SendOrPostCallback LoadBizObjectsOperationCompleted;
        
        private System.Threading.SendOrPostCallback RemoveBizObjectOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public BizObjectService() {
            this.Url = global::H3.Wyeth.MainPush.Properties.Settings.Default.H3_Wyeth_MainPush_com_h3yun_www_BizObjectService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public Authentication AuthenticationValue {
            get {
                return this.authenticationValueField;
            }
            set {
                this.authenticationValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CreateBizObjectsCompletedEventHandler CreateBizObjectsCompleted;
        
        /// <remarks/>
        public event CreateBizObjectCompletedEventHandler CreateBizObjectCompleted;
        
        /// <remarks/>
        public event UpdateBizObjectCompletedEventHandler UpdateBizObjectCompleted;
        
        /// <remarks/>
        public event LoadBizObjectCompletedEventHandler LoadBizObjectCompleted;
        
        /// <remarks/>
        public event LoadBizObjectsCompletedEventHandler LoadBizObjectsCompleted;
        
        /// <remarks/>
        public event RemoveBizObjectCompletedEventHandler RemoveBizObjectCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CreateBizObjects", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CreateBizObjects(string schemaCode, string[] objDatas, bool submit) {
            object[] results = this.Invoke("CreateBizObjects", new object[] {
                        schemaCode,
                        objDatas,
                        submit});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CreateBizObjectsAsync(string schemaCode, string[] objDatas, bool submit) {
            this.CreateBizObjectsAsync(schemaCode, objDatas, submit, null);
        }
        
        /// <remarks/>
        public void CreateBizObjectsAsync(string schemaCode, string[] objDatas, bool submit, object userState) {
            if ((this.CreateBizObjectsOperationCompleted == null)) {
                this.CreateBizObjectsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateBizObjectsOperationCompleted);
            }
            this.InvokeAsync("CreateBizObjects", new object[] {
                        schemaCode,
                        objDatas,
                        submit}, this.CreateBizObjectsOperationCompleted, userState);
        }
        
        private void OnCreateBizObjectsOperationCompleted(object arg) {
            if ((this.CreateBizObjectsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateBizObjectsCompleted(this, new CreateBizObjectsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CreateBizObject", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CreateBizObject(string schemaCode, string objData, bool submit) {
            object[] results = this.Invoke("CreateBizObject", new object[] {
                        schemaCode,
                        objData,
                        submit});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CreateBizObjectAsync(string schemaCode, string objData, bool submit) {
            this.CreateBizObjectAsync(schemaCode, objData, submit, null);
        }
        
        /// <remarks/>
        public void CreateBizObjectAsync(string schemaCode, string objData, bool submit, object userState) {
            if ((this.CreateBizObjectOperationCompleted == null)) {
                this.CreateBizObjectOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateBizObjectOperationCompleted);
            }
            this.InvokeAsync("CreateBizObject", new object[] {
                        schemaCode,
                        objData,
                        submit}, this.CreateBizObjectOperationCompleted, userState);
        }
        
        private void OnCreateBizObjectOperationCompleted(object arg) {
            if ((this.CreateBizObjectCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateBizObjectCompleted(this, new CreateBizObjectCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateBizObject", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string UpdateBizObject(string schemaCode, string objectId, string objData) {
            object[] results = this.Invoke("UpdateBizObject", new object[] {
                        schemaCode,
                        objectId,
                        objData});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateBizObjectAsync(string schemaCode, string objectId, string objData) {
            this.UpdateBizObjectAsync(schemaCode, objectId, objData, null);
        }
        
        /// <remarks/>
        public void UpdateBizObjectAsync(string schemaCode, string objectId, string objData, object userState) {
            if ((this.UpdateBizObjectOperationCompleted == null)) {
                this.UpdateBizObjectOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateBizObjectOperationCompleted);
            }
            this.InvokeAsync("UpdateBizObject", new object[] {
                        schemaCode,
                        objectId,
                        objData}, this.UpdateBizObjectOperationCompleted, userState);
        }
        
        private void OnUpdateBizObjectOperationCompleted(object arg) {
            if ((this.UpdateBizObjectCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateBizObjectCompleted(this, new UpdateBizObjectCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LoadBizObject", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string LoadBizObject(string schemaCode, string objectId) {
            object[] results = this.Invoke("LoadBizObject", new object[] {
                        schemaCode,
                        objectId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void LoadBizObjectAsync(string schemaCode, string objectId) {
            this.LoadBizObjectAsync(schemaCode, objectId, null);
        }
        
        /// <remarks/>
        public void LoadBizObjectAsync(string schemaCode, string objectId, object userState) {
            if ((this.LoadBizObjectOperationCompleted == null)) {
                this.LoadBizObjectOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoadBizObjectOperationCompleted);
            }
            this.InvokeAsync("LoadBizObject", new object[] {
                        schemaCode,
                        objectId}, this.LoadBizObjectOperationCompleted, userState);
        }
        
        private void OnLoadBizObjectOperationCompleted(object arg) {
            if ((this.LoadBizObjectCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoadBizObjectCompleted(this, new LoadBizObjectCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LoadBizObjects", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string LoadBizObjects(string schemaCode, string filterStr) {
            object[] results = this.Invoke("LoadBizObjects", new object[] {
                        schemaCode,
                        filterStr});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void LoadBizObjectsAsync(string schemaCode, string filterStr) {
            this.LoadBizObjectsAsync(schemaCode, filterStr, null);
        }
        
        /// <remarks/>
        public void LoadBizObjectsAsync(string schemaCode, string filterStr, object userState) {
            if ((this.LoadBizObjectsOperationCompleted == null)) {
                this.LoadBizObjectsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoadBizObjectsOperationCompleted);
            }
            this.InvokeAsync("LoadBizObjects", new object[] {
                        schemaCode,
                        filterStr}, this.LoadBizObjectsOperationCompleted, userState);
        }
        
        private void OnLoadBizObjectsOperationCompleted(object arg) {
            if ((this.LoadBizObjectsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoadBizObjectsCompleted(this, new LoadBizObjectsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RemoveBizObject", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string RemoveBizObject(string schemaCode, string objectId) {
            object[] results = this.Invoke("RemoveBizObject", new object[] {
                        schemaCode,
                        objectId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void RemoveBizObjectAsync(string schemaCode, string objectId) {
            this.RemoveBizObjectAsync(schemaCode, objectId, null);
        }
        
        /// <remarks/>
        public void RemoveBizObjectAsync(string schemaCode, string objectId, object userState) {
            if ((this.RemoveBizObjectOperationCompleted == null)) {
                this.RemoveBizObjectOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRemoveBizObjectOperationCompleted);
            }
            this.InvokeAsync("RemoveBizObject", new object[] {
                        schemaCode,
                        objectId}, this.RemoveBizObjectOperationCompleted, userState);
        }
        
        private void OnRemoveBizObjectOperationCompleted(object arg) {
            if ((this.RemoveBizObjectCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RemoveBizObjectCompleted(this, new RemoveBizObjectCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/", IsNullable=false)]
    public partial class Authentication : System.Web.Services.Protocols.SoapHeader {
        
        private string engineCodeField;
        
        private string corpIdField;
        
        private string secretField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public string EngineCode {
            get {
                return this.engineCodeField;
            }
            set {
                this.engineCodeField = value;
            }
        }
        
        /// <remarks/>
        public string CorpId {
            get {
                return this.corpIdField;
            }
            set {
                this.corpIdField = value;
            }
        }
        
        /// <remarks/>
        public string Secret {
            get {
                return this.secretField;
            }
            set {
                this.secretField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void CreateBizObjectsCompletedEventHandler(object sender, CreateBizObjectsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateBizObjectsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateBizObjectsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void CreateBizObjectCompletedEventHandler(object sender, CreateBizObjectCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateBizObjectCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateBizObjectCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void UpdateBizObjectCompletedEventHandler(object sender, UpdateBizObjectCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateBizObjectCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateBizObjectCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void LoadBizObjectCompletedEventHandler(object sender, LoadBizObjectCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoadBizObjectCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LoadBizObjectCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void LoadBizObjectsCompletedEventHandler(object sender, LoadBizObjectsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoadBizObjectsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LoadBizObjectsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void RemoveBizObjectCompletedEventHandler(object sender, RemoveBizObjectCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RemoveBizObjectCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RemoveBizObjectCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591